// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC44F_D6vlv6CKeU-Wav44c-k1zPU6CTa8',
    appId: '1:1043585898165:android:2bb612e23da15aa34cd0fc',
    messagingSenderId: '1043585898165',
    projectId: 'smoke-money',
    storageBucket: 'smoke-money.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46uBUvmVQKsSL7HIXZG58MD9jXQCFX7c',
    appId: '1:948878883710:ios:5363ad2b9fbe06b2a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpSwulVtmZr6FholdWxq-BUxtQ_MhoPE',
    appId: '1:1043585898165:web:fed44dbd909c6a474cd0fc',
    messagingSenderId: '1043585898165',
    projectId: 'smoke-money',
    authDomain: 'smoke-money.firebaseapp.com',
    storageBucket: 'smoke-money.firebasestorage.app',
    measurementId: 'G-05MVNLLG04',
  );

}